### ISSUE TITLE
Lazy read of collections and images

### ISSUE THREAD

**Issue by bcipolli** [NeuroVault/pyneurovault#15]
Currently, `api.NeuroVault` fetches collections and images on object construction. This is very slow (~1 minute), and may not be relevant to the user.

``` python
    def __init__(self):
        self.collections = self.get_collections()      
        self.images = self.get_images()                
        print self
```

I suggest only downloading these data when needed. If you really want this behavior available, I suggest toggling it with a construction flag (perhaps `preload=True` or `on_demand=False`)

**Comment by vsoch** [comment]
I created the initial API as object oriented only because it was the functionality that worked best for me, and I agree that it needs to be refactored. I don't have a good estimate for when I can do this.

**Comment by vsoch** [comment]
Just kidding. I'm doing it right now. This is annoyingly bad. :)
