### ISSUE TITLE
Simplify package dependencies

### ISSUE THREAD

**Issue by bcipolli** [NeuroVault/pyneurovault#16]
Right now, this package depends on `nipype` and `nilearn`. 

The `nipype` is a larger dependency for a single utility function--seems better to copy it out.
The `nilearn` dependency is only for an example. Seems odd to install it when installing `pyneurovault`, as the example isn't accessible.

**Comment by vsoch** [comment]
I agree that Nipype is too heavy for this API, and it has been removed. Nilearn is important for the resampling of images during download, and will be required for now.
