### ISSUE TITLE
cannot import 'images_from_collections'

### ISSUE THREAD

**Issue by saurabhr** [NeuroVault/pyneurovault#34]
I am getting this import error...is it because I am using python 3.10?

`ImportError: cannot import name 'images_from_collections' from 'pyneurovault.api' (/Users/saurabh.ranjan/opt/anaconda3/envs/brain/lib/python3.10/site-packages/pyneurovault/api.py)`

**Comment by vsoch** [comment]
I think you are missing the get_ prefix! https://github.com/NeuroVault/pyneurovault/blob/fb5fe92a5a5f9d9f47f10118ebee47df1efae01b/pyneurovault/api.py#L111

**Comment by saurabhr** [comment]
thanks, i was trying this line: https://github.com/NeuroVault/pyneurovault/blob/fb5fe92a5a5f9d9f47f10118ebee47df1efae01b/examples/query_example.py#L5

seems like the example is outdated (?) as I checked in the script you attached there is no function images_from_collections there

**Comment by vsoch** [comment]
It’s likely a typo! Would you care to PR to fix?
