### ISSUE TITLE
Function to get article info

### ISSUE THREAD

**Issue by vsoch** [NeuroVault/pyneurovault#6]
We would want to:
- filter down to subset of images interested in
- for each image, get pmid/doi
- [idea] could get complete info from pubmed
- [idea] could get json data structure directly from brainspell

will be integrated into [cogatlas](https://github.com/vsoch/cogat/tree/enh/nifti_wrapper/api-python) API to annotate images!

Links of use:
- [collection based on DOI](http://neurovault.org/api/collections/?DOI=10.1016/j.neurobiolaging.2012.11.002) from Chris
- [brainspell with pmid](http://neurovault.org/api/collections/?DOI=10.1016/j.neurobiolaging.2012.11.002)

**Comment by chrisgorgo** [comment]
https://github.com/NeuroVault/NeuroVault/blob/683763f6c5e8a2d80e94ded7761405614feb87c7/neurovault/apps/statmaps/utils.py#L152

**Comment by vsoch** [comment]
Added https://github.com/NeuroVault/pyneurovault/commit/6b505d38bb82020e027d2a4dc94c1ae2702748e4
